---
name: Array-Tour
version: 0.05
author:
  - 'John M. Gamble <jgamble@cpan.org>'
abstract: Base class for Array Tours.
license: perl
requires:
  perl: 5.8.0
build_requires:
  Test::Simple: 0
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Array::Tour:
    file: lib/Array/Tour.pm
    version: 0.05
  Array::Tour::RandomWalk:
    file: lib/Array/Tour/RandomWalk.pm
    version: 0.05
  Array::Tour::Serpentine:
    file: lib/Array/Tour/Serpentine.pm
    version: 0.05
  Array::Tour::Spiral:
    file: lib/Array/Tour/Spiral.pm
    version: 0.05
resources:
  license: http://dev.perl.org/licenses/
